### ISSUE TITLE
Invalid customer data response

### ISSUE THREAD

**Issue by germanflighel** [mercadopago/sdk-ruby#58] opened 2021-11-04 21:29 UTC
**Description**
Creation of a customer with a regular email containing a `_` character fails. I'm getting the following error code, not present in the API documentation:
```
{"status"=>"400", "response"=>{"message"=>"invalid parameters ", "error"=>"bad_request", "status"=>400, "cause"=>[{"code"=>"130", "description"=>"Invalid customer data"}]}}
```

**To Reproduce**
Try to create a customer with the v1 api via POST to `v1/customers/`, with a sample email containing underscores, such as `test_email@gmail.com`.

**Expected behavior**
I expected the customer to be created as normal.

**Environment (please complete the following information):**
Tested using Sandbox and in failing in production too.

- OS: Linux
- Ruby version: [2.6.6]
- SDK version: [1.3.0]

Thanks in advance!

**Comment by eltinMeli** [comment] 2021-11-05 19:37
Hi @germanflighel , I hope you are alright.

First of all thank you for reporting this bug.

I ran locally and was able to simulate the bug you reported and realized that it only occurs in version 1.3.0 :(, in higher versions the bug does not exist. As a suggestion you can update to the latest version 2.0.2, because in the future version 1.3.0 will be deprecated.

In parallel we will fix this bug and let you know when it's done through this issue.

Together we are stronger

Big hug

**Comment by germanflighel** [comment] 2021-11-08 12:25
Hi @eltinMeli! Thanks for the thoughtful and kind response! 
Awesome. I'll wait for your updates. 

Big hug to you too!

**Comment by eltinMeli** [comment] 2021-11-12 12:50
Hello @germanflighel , doing a deeper analysis I identified that the problem is not found in the Ruby SDK, but in the API /v1/costumers. This API is intermittent, I confirmed with some colleagues who gave me the same scenario. I opened an internal ticket for the team responsible for this API to carry out the analysis in order to point out the cause and solve it.

To validate the scenario, you can use the CURL command in your preferred terminal, modifying the value of the YOUR_ACCESS_TOKEN field.

Example
`curl -X POST \
    'https://api.mercadopago.com/v1/customers' \
    -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' \
    -H 'Content-Type: application/json' \
    -d '{"email": "gesto_santos@gmail.com"}'`

I leave here the Mercado Pago developer support channel, if you want to contact directly those responsible for this API.
https://www.mercadopago.com.br/developers/en/support

For now I'm going to close this bug issue, as it applies to the API.

Hug

**Closed** 2021-11-16 13:59 UTC
Labels: bug
